version: '3.8'

services:
  transcription-service:
    build: .
    container_name: transcription_service
    ports:
      - "8000:8000" # exposes port 8000 on the host
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      # database connection details - please update these with your actual credentials
      - DB_HOST=transcriber-db # service name of the postgres container
      - DB_PORT=5432
      - DB_NAME=transcriber_db # replace with your database name
      - DB_USER=gojack10       # replace with your database user
      - DB_PASSWORD=moso10     # replace with your database password
      - WHISPER_MODEL=turbo  # change as needed (e.g., tiny.en, small.en, medium.en)
      - PYTHONUNBUFFERED=1
      # if your app needs timezone data, uncomment and set appropriately
      # - TZ=america/los_angeles
    volumes:
      - ./list.txt:/app/list.txt   # maps your local list.txt to the one in the container
      - ./tmp:/app/tmp             # maps your local tmp folder
      - ./whisper-cache:/root/.cache/whisper # persists whisper models to ./whisper-cache on your host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    depends_on:
      - transcriber-db
    networks:
      - transcriber_network
    restart: unless-stopped

  transcriber-db:
    image: postgres:15
    container_name: transcriber-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: gojack10
      POSTGRES_PASSWORD: moso10
      POSTGRES_DB: transcriber_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /mnt/massstorage/transcription-db:/var/lib/postgresql/data/pgdata # new host path
    ports:
      - "0.0.0.0:5432:5432"
    networks:
      - transcriber_network

networks:
  transcriber_network:
    driver: bridge
    name: transcriber_app_network