"""Add pst_time column back to transcribed table

Revision ID: 3ecf12a34a6d
Revises: d995b1812b67
Create Date: 2025-06-16 10:24:17.929903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ecf12a34a6d'
down_revision: Union[str, None] = 'd995b1812b67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcribed', sa.Column('pst_time', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcribed', 'pst_time')
    # ### end Alembic commands ###
