"""Remove pst_time from transcribed table

Revision ID: d995b1812b67
Revises: 
Create Date: 2025-06-16 10:19:54.314909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd995b1812b67'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('downloaded_videos', 'url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('downloaded_videos', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('downloaded_videos', 'download_date',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=False,
               postgresql_using='download_date::timestamp without time zone')
    op.alter_column('downloaded_videos', 'local_path',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('downloaded_videos_url_key'), 'downloaded_videos', type_='unique')
    op.create_index(op.f('ix_downloaded_videos_id'), 'downloaded_videos', ['id'], unique=False)
    op.create_index(op.f('ix_downloaded_videos_url'), 'downloaded_videos', ['url'], unique=True)
    op.alter_column('transcribed', 'utc_time',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using='utc_time::timestamp with time zone')
    op.alter_column('transcribed', 'url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('transcribed', 'video_title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint(op.f('transcribed_url_key'), 'transcribed', type_='unique')
    op.create_index(op.f('ix_transcribed_id'), 'transcribed', ['id'], unique=False)
    op.create_index(op.f('ix_transcribed_url'), 'transcribed', ['url'], unique=True)
    op.drop_column('transcribed', 'pst_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcribed', sa.Column('pst_time', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_transcribed_url'), table_name='transcribed')
    op.drop_index(op.f('ix_transcribed_id'), table_name='transcribed')
    op.create_unique_constraint(op.f('transcribed_url_key'), 'transcribed', ['url'], postgresql_nulls_not_distinct=False)
    op.alter_column('transcribed', 'video_title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('transcribed', 'url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('transcribed', 'utc_time',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_downloaded_videos_url'), table_name='downloaded_videos')
    op.drop_index(op.f('ix_downloaded_videos_id'), table_name='downloaded_videos')
    op.create_unique_constraint(op.f('downloaded_videos_url_key'), 'downloaded_videos', ['url'], postgresql_nulls_not_distinct=False)
    op.alter_column('downloaded_videos', 'local_path',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('downloaded_videos', 'download_date',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('downloaded_videos', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('downloaded_videos', 'url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
